name: grocery_app
version: 1.0.0
description: A new Get Server application.
environment: 
  sdk: '>=2.4.0 <3.0.0'

dependencies: 
  get_server: 1.2.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/